import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '../components/footer/footer'
const inter = Inter({ subsets: ['latin'] })
import Navbar from '../components/Navbar/Navbar'
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { Providers } from './GlobalRedux/provider'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <html lang="en">
      <body className={"font-mono"}>
      <Providers>
        <Navbar/>
        <div className="">
      </div>
        {children}
        <Footer/>
        <ToastContainer autoClose={2000}/>
        </Providers>
      </body>
    </html>
    
  )
}
